name: deployment

on:
  push:
    branches: ["main"]

jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/setup-node@v4 
        with:
          node-version: '18'
        
  deploy-echo:
    needs: develop
    runs-on: ubuntu-latest
    steps: 
      - uses:  actions/checkout@v4 
      - run: echo "Hello, World!"
      - run: echo "Esto es un mensaje de prueba"
      - run: echo "testeo del actions"
      - run: echo "MENSAJES ENVIADOS CON EXITO"
  
  version-info:
    name: Version Info
    runs-on: ubuntu-latest
    needs: deploy-echo
    outputs:
        version_beta: ${{steps.get_version.outputs.beta_version}}
    steps:
      - name: Get Version Info
        id: get_version
        run: echo "beta_version=1.0.2-beta" >> $GITHUB_OUTPUT
      
  get-version:
    runs-on: ubuntu-latest
    name: obtener version con outputs
    needs: version-info
    steps:
      - name: Get Version Info
        run: echo "la version es ${{ needs.version-info.outputs.version_beta }}"

