name: deployment

on:
  push:
    branches: ["main"]

jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
        
  deploy-echo:
    needs: develop
    runs-on: ubuntu-latest
    steps: 
      - uses:  actions/checkout@v4 
      - run: echo "Hello, World!"
      - run: echo "Esto es un mensaje de prueba"
      - run: echo "testeo del actions"
      - run: echo "MENSAJES ENVIADOS CON EXITO"


