name: Secretos y Variables de ENTORNO

on: push

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: manejo de Secretos
        run: echo "${{secrets.SSH_KEY}}"

      - name: manejo de variables de ENTORNO
        run: echo "${{env.NAME_SSH}}"